### ISSUE TITLE
Replace layermod with exit

### ISSUE THREAD

**Issue by pmer** [pariahsoft/Driftwood#31]
Layermods are a special case of exit where only the layer is modified.

We should be able to eliminate these and just use exits.  This will automatically give us support for "wide layermods" after #28 Support Wide Exits is finished.  It will also reduce the complexity of the code and will help unify all code that teleports entities.

We could do this in one of two ways:

### Syntactic sugar

The "layermod" tile property is just syntactic sugar for "exit to same area/tile."  The layermod tile property would be parsed for during area load and an exit property inserted.

### Elimination

Just remove the concept of layermods entirely.  Always use and refer to exits for all teleportation needs.

**Comment by seisatsu** [comment]
The movement code is actually alright once I've really looked at it. And, as far as I can tell layermod is currently a teleport. However, we are actually missing a function to change areas from a script.

**Comment by seisatsu** [comment]
Alright, we now support exits changing layer, x, or y within the same area by calling a teleport if the area field in the exit arguments is empty. Now we just need to support incrementing or decrementing with the plus or minus sign and it'll be finished.

**Comment by seisatsu** [comment]
It's done, but _can_walk() is kind of huge now.
